version: "3"
services:
  postgres:
    container_name: api-db-postgres
    image: postgres:14
    ports:
      - "5432:5432"
    command: [ "postgres", "-cshared_preload_libraries=pg_stat_statements" ]
    #command: ["postgres", "-cshared_preload_libraries=pg_stat_statements", "-clog_statement=all"]
    environment:
      POSTGRES_USER: dev-node
      POSTGRES_PASSWORD: insecure-change-me-in-prod
      POSTGRES_DB: dev-node
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5432" ]
      interval: 30s
      timeout: 10s
      retries: 15
  pgweb:
    container_name: api-db-pgweb
    image: sosedoff/pgweb:0.11.12
    restart: on-failure
    ports:
      - "8081:8081"
    command: [ "pgweb", "--bind=0.0.0.0", "--listen=8081", "--binary-codec=hex" ]
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://dev-node:insecure-change-me-in-prod@postgres:5432/dev-node?sslmode=disable
    depends_on:
      - postgres
  database:
    container_name: api-db-clickhouse
    image: clickhouse/clickhouse-server
    user: "101:101"
    hostname: clickhouse
    volumes:
      - ./data/clickhouse-server/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./data/clickhouse-server/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9005:9005"

  substream_setup:
    image: derzwerggimli/substreams-solana-staratlas-gm
    entrypoint: "substreams-sink-sql setup 'psql://dev-node:insecure-change-me-in-prod@api-db-postgres:5432/dev-node?sslmode=disable' substreams.yaml"

  substream_run:
    image: derzwerggimli/substreams-solana-staratlas-gm
    entrypoint: "substreams-sink-sql run 'psql://dev-node:insecure-change-me-in-prod@api-db-postgres:5432/dev-node?sslmode=disable' substreams.yaml -e mainnet.sol.streamingfast.io:443 142384016: --irreversible-only"
    environment:
      STREAMINGFAST_KEY: ${STREAMINGFAST_KEY}

  substream_run2:
    image: derzwerggimli/substreams-solana-staratlas-gm
    entrypoint: "echo Hello"
    environment:
      STREAMINGFAST_KEY: ${STREAMINGFAST_KEY}
