version: "3"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: devpass
    volumes:
      - ./data/timescale:/home/postgres/pgdata/data


  substream_setup:
    image: derzwerggimli/substreams-solana-staratlas-gm
    depends_on: [ timescaledb ]
    entrypoint: "substreams-sink-sql setup psql://db:devpass@timescaledb:5432/db?sslmode=disable substreams.yaml"
    environment:
      STREAMINGFAST_KEY: ${STREAMINGFAST_KEY}

  substream_run:
    image: derzwerggimli/substreams-solana-staratlas-gm
    depends_on: [ timescaledb ]
    environment:
      STREAMINGFAST_KEY: ${STREAMINGFAST_KEY}
      #DSN: psql://dev-node:insecure-change-me-in-prod@postgres:5432/dev-node?sslmode=disable
      SINK_DB: psql://db:devpass@timescaledb:5432/db?sslmode=disable
      SINK_MODE: run
      SINK_FLAGS: '--final-blocks-only'

  api:
    image: derzwerggimli/api-roguemarket-2:latest
    depends_on: [ timescaledb ]
    ports:
      - "9999:9999"
    environment:
      DB_URL: psql://db:devpass@timescaledb:5432/db?sslmode\=disable
      APIPORT: 9999

